/*
auther: Naman Tamrakar
date: 2023-07-19

level: easy
url: https://leetcode.com/problems/find-the-difference/
question: You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

#include <stdio.h>
#include <stdlib.h>

char findTheDifference_c(char * s, char * t){
    int i=0;
    int ans=t[i];
    while (s[i]!='\0') {
        ans += t[i+1] - s[i];
        i++;
    }
    return ans;
}

__attribute__((naked))
char findTheDifference(char * s, char * t){
    __asm__(
            // int i=0;
            "movl $0, %edx;"
            // int ans=t[i];
            "movb (%rsi,%rdx,1), %al;"

        "l1:;"
            // while (s[i]!='\0') {
            "cmpb $0, (%rdi,%rdx,1);"
            "je end;"

            // ans -= s[i];
            "subb (%rdi,%rdx,1), %al;"
            // i++;
            "incl %edx;"
            // ans += t[i+1] ;
            "addb (%rsi,%rdx,1), %al;"

            "jmp l1;"

        "end:;"
            // return ans;
            "ret;"
    );
}

const int MAX_VAL = 1001;

int main() {
    char s[MAX_VAL], t[MAX_VAL];
    scanf("%s", s);
    scanf("%s", t);
    printf("%c\n", findTheDifference(s, t));
    return 0;
}

